# Generated by Django 5.1.15 on 2026-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_deliveryslotbooking_slot_delete_deliveryslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='estimated_delivery_text',
            field=models.CharField(blank=True, help_text="e.g. '1-2 Business Days'. Overrides the global default.", max_length=255, verbose_name='Estimated Delivery'),
        ),
    ]
