# Generated by Django 5.1.15 on 2026-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitesettings_order_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_enquiry',
            field=models.BooleanField(default=True, help_text='Enable to receive notifications for contact inquiries.', verbose_name='Enquiry Notification'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_low_stock',
            field=models.BooleanField(default=True, help_text='Enable to receive notifications for low stock alerts.', verbose_name='Low Stock Notification'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_new_order',
            field=models.BooleanField(default=True, help_text='Enable to receive notifications for new orders.', verbose_name='New Order Notification'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='order_notification_email',
            field=models.EmailField(blank=True, help_text='Email address to receive system notifications. Leave blank to disable all.', max_length=254, verbose_name='Notification Email'),
        ),
    ]
