# Generated by Django 5.1.15 on 2026-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sitesettings_notify_enquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Replied At'),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='reply_message',
            field=models.TextField(blank=True, null=True, verbose_name='Reply Message'),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='reply_subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reply Subject'),
        ),
    ]
