# Generated by Django 5.1.15 on 2026-09-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contactinquiry_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='GA4 Measurement ID (e.g. G-XXXXXXXXXX)', max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='Meta Pixel ID (e.g. 1234567890)', max_length=50, verbose_name='Meta Pixel ID'),
        ),
    ]
