# Generated by Django 5.1.15 on 2026-09-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sitesettings_google_analytics_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_brands',
            field=models.BooleanField(default=True, help_text='Enable or disable Brand features across the entire site.', verbose_name='Enable Brands'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_delhivery',
            field=models.BooleanField(default=True, help_text='Enable or disable Delhivery shipping integration across the site.', verbose_name='Enable Delhivery'),
        ),
    ]
