# Generated by Django 5.1.15 on 2026-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sitesettings_enable_brands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_estimated_delivery_text',
            field=models.CharField(blank=True, default='Dispatch in 24 hours. Delivery in 2-5 Business Days.', help_text='Shown on PDP and as fallback if city has no override.', max_length=255, verbose_name='Default Estimated Delivery'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fallback flat shipping rate.', max_digits=10, verbose_name='Default Shipping Charge'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orders over this amount get free shipping (leave blank for no free shipping).', max_digits=10, null=True, verbose_name='Free Shipping Threshold'),
        ),
    ]
