# Generated by Django 6.0.3 on 2026-09-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sitesettings_default_estimated_delivery_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_cod',
            field=models.BooleanField(default=True, help_text='Enable or disable Cash on Delivery payment option at checkout.', verbose_name='Enable Cash on Delivery (COD)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_razorpay',
            field=models.BooleanField(default=True, help_text='Enable or disable Razorpay online payment option at checkout.', verbose_name='Enable Razorpay'),
        ),
    ]
