# Generated by Django 6.0.3 on 2026-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sitesettings_enable_cod_sitesettings_enable_razorpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cybersource_key_id',
            field=models.CharField(blank=True, help_text='CyberSource REST API Key ID.', max_length=120, verbose_name='CyberSource Key ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cybersource_merchant_id',
            field=models.CharField(blank=True, help_text='CyberSource Merchant ID.', max_length=120, verbose_name='CyberSource Merchant ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cybersource_run_environment',
            field=models.CharField(choices=[('apitest.cybersource.com', 'Test / Sandbox (apitest.cybersource.com)'), ('api.cybersource.com', 'Production / Live (api.cybersource.com)')], default='apitest.cybersource.com', help_text='Run environment for CyberSource API requests.', max_length=50, verbose_name='CyberSource Environment'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cybersource_secret_key',
            field=models.CharField(blank=True, help_text='CyberSource Shared Secret Key.', max_length=255, verbose_name='CyberSource Secret Key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_cybersource',
            field=models.BooleanField(default=True, help_text='Enable or disable CyberSource payment option at checkout.', verbose_name='Enable CyberSource'),
        ),
    ]
