# Generated by Django 5.1.15 on 2026-09-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sitesettings_cybersource_key_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cybersource_run_environment',
            field=models.CharField(choices=[('apitest.cybersource.com', 'Test'), ('api.cybersource.com', 'Live')], default='apitest.cybersource.com', help_text='Run environment for CyberSource API requests.', max_length=50, verbose_name='CyberSource Environment'),
        ),
    ]
