# Generated by Django 6.0.3 on 2026-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_sitesettings_cybersource_run_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='afterpay_environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox (Test)'), ('production', 'Production (Live)')], default='sandbox', help_text='Environment for Afterpay API requests.', max_length=50, verbose_name='Afterpay Environment'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='afterpay_merchant_id',
            field=models.CharField(blank=True, help_text='Afterpay Merchant ID.', max_length=120, verbose_name='Afterpay Merchant ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='afterpay_secret_key',
            field=models.CharField(blank=True, help_text='Afterpay Secret Key.', max_length=255, verbose_name='Afterpay Secret Key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_afterpay',
            field=models.BooleanField(default=True, help_text='Enable or disable Afterpay payment option at checkout.', verbose_name='Enable Afterpay'),
        ),
    ]
