# Generated by Django 5.1.15 on 2026-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sitesettings_afterpay_environment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='afterpay_environment',
            field=models.CharField(choices=[('sandbox', 'Test'), ('production', 'Live')], default='sandbox', help_text='Environment for Afterpay API requests.', max_length=50, verbose_name='Afterpay Environment'),
        ),
    ]
