# Generated by Django 5.1.15 on 2026-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_sitesettings_afterpay_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='afterpay_environment',
            field=models.CharField(choices=[('global-api-sandbox.afterpay.com', 'Test'), ('global-api.afterpay.com', 'Live')], default='global-api-sandbox.afterpay.com', help_text='Run environment for Afterpay API requests.', max_length=50, verbose_name='Afterpay Environment'),
        ),
    ]
