# Generated by Django 6.0.3 on 2026-09-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_sitesettings_afterpay_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_newsletter',
            field=models.BooleanField(default=True, help_text='Enable or disable Newsletter subscription features and display on home page and sidebar.', verbose_name='Enable Newsletter'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_pages',
            field=models.BooleanField(default=True, help_text='Enable or disable custom Pages feature and display in footer and sidebar.', verbose_name='Enable Pages'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_delhivery',
            field=models.BooleanField(default=False, help_text='Enable or disable Delhivery shipping integration across the site.', verbose_name='Enable Delhivery'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#1B4D3E', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#C5A059', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Sarocchi Luxe Designs', max_length=120),
        ),
    ]
