# Generated by Django 5.1.15 on 2026-09-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customerprofile_notify_via_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='New Zealand', max_length=120, verbose_name='Country'),
        ),
    ]
