# Generated by Django 5.1.15 on 2026-09-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_alter_sizechart_content_html"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvideo",
            name="video_url",
        ),
        migrations.AddField(
            model_name="productvideo",
            name="video_file",
            field=models.FileField(
                default="", upload_to="products/videos/", verbose_name="Video File"
            ),
            preserve_default=False,
        ),
    ]
