# Generated by Django 5.1.15 on 2026-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_collection_productlabel_producttag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.productattributevalue', verbose_name='Attribute values'),
        ),
    ]
