# Generated by Django 5.1.15 on 2026-09-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_product_attribute_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='Product-specific care instructions.', verbose_name='Care instructions'),
        ),
    ]
