# Generated by Django 5.1.15 on 2026-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_product_care_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku_suffix',
            field=models.CharField(blank=True, help_text='Full globally unique SKU for this variant.', max_length=128, null=True, unique=True, verbose_name='Variant SKU'),
        ),
    ]
