# Generated by Django 5.1.15 on 2026-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_picked_up_in_transit_out_for_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_text',
            field=models.CharField(blank=True, help_text='Snapshot of the delivery estimate at the time of order.', max_length=255, verbose_name='Estimated Delivery Text'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, help_text='Name of the courier or shipping service.', max_length=120, verbose_name='Shipping Provider'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Manual or gateway tracking number for the shipment.', max_length=120, verbose_name='Tracking Number'),
        ),
    ]
