# Generated by Django 5.1.15 on 2026-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_estimated_delivery_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('checkout_pending', 'Payment Pending'), ('placed_cod', 'COD Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('ready_to_ship', 'Ready to Ship'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='checkout_pending', max_length=20, verbose_name='Order status'),
        ),
    ]
