# Generated by Django 5.1.15 on 2026-09-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_provider_url',
            field=models.URLField(blank=True, help_text='URL for tracking the shipment.', verbose_name='Shipping Provider URL'),
        ),
    ]
